# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
# Define VMs with static private IP addresses, vcpu, memory and vagrant-box.
  boxes = [
    {
      :box => "debian/bullseye64",
      :name => "managed-host1",
      :ram => 1024,
      :vcpu => 1,
      :ip => "192.168.56.10"
    },
    {
      :box => "debian/bullseye64",
      :name => "ansible-host",
      :ram => 2048,
      :vcpu => 1,
      :ip => "192.168.56.1"
    }
  ]

  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|

      config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
      config.ssh.insert_key = false
      config.vm.box = opts[:box]
      config.vm.hostname = opts[:name]
      config.vm.provider :virtualbox do |v|
        v.memory = opts[:ram]
        v.cpus = opts[:vcpu]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
      config.vm.network :private_network, ip: opts[:ip]

      config.vm.synced_folder "shared/", "/shared"

      # config.vm.provision :file do |file|
      #    file.source     = './keys/vagrant'
      #    file.destination    = '/tmp/vagrant'
      #   end
      # config.vm.provision :file do |file|
      #   file.source     = './inventory-test.yaml'
      #   file.destination    = '/home/vagrant/inventory-test.yaml'
      #  end
      # config.vm.provision :shell, path: "bootstrap-node.sh"
      # config.vm.provision :ansible do |ansible|
      #   ansible.verbose = "v"
      #   ansible.playbook = "playbook.yml"
      # end
   end
  end
end
